"""Verify active deterministic CSV/TXT outputs against frozen baselines.

Only outputs generated by the revised default CI pipeline are checked.
Figures are excluded because rendering metadata can vary by environment.
Retired legacy analyses are retained for audit reproducibility but are not
part of the revised evidentiary package or required by this verifier.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
GOLDEN = BASE / "golden"

EXPECTED_FILES = (
    # Core retrospective characterization
    "output/table1_cross_domain.csv",
    "output/table2_mult_vs_add.csv",
    "output/table3_permutation.csv",
    "output/table4_failure_modes.csv",
    "output/table_S1_plimit_sensitivity.csv",
    "output/table_S2_variable_robustness.csv",
    "output/table_S4_nonredundancy.csv",
    "output/summary.txt",

    # Active supplementary analyses
    "output/benchmark_full.csv",
    "output/benchmark_pivot.csv",
    "output/benchmark_summary.txt",
    "output/table_enhanced_time_normalized.csv",
    "output/table_enhanced_sliding_controls.csv",
    "output/table_enhanced_cutoff_sensitivity.csv",
    "output/table_v13_sliding_controls.csv",
    "output/table_v13_block_permutation.csv",

    # Primary non-overlapping crisis-control reanalysis
    "output/table_nonoverlap_primary.csv",
    "output/table_nonoverlap_formulations.csv",
    "output/table_nonoverlap_ablation.csv",

    # Extended sensitivity analyses using the revised comparison design
    "output/table_nonoverlap_variable_substitution.csv",
    "output/table_ST15_nonoverlap_delta_k.csv",
    "output/table_threshold_grid_labels.csv",
    "output/table_threshold_grid_retention.csv",
    "output/table_ST17_matched_threshold_sensitivity.csv",

    "output/table_variable_substitution.csv",
    "output/table_additional_cases.csv",
    "output/table_additional_permutation.csv",
    "output/table_additional_time_normalized.csv",
    "output/table_additional_nonredundancy.csv",
    "output/table_ST15_delta_k_sensitivity.csv",
    "output/table_ST17_retrospective_trajectory.csv",

    # Additional-case frozen data generated by the active pipeline
    "data/crisis_dotcom_pi.csv",
    "data/control_dotcom_pi.csv",
    "data/crisis_repo_pi.csv",
    "data/control_repo_pi.csv",
    "data/crisis_thailand_pi.csv",
    "data/control_thailand_pi.csv",
)

RETIRED_LEGACY_FILES = (
    "output/table_ST16_matched_pipeline.csv",
    "output/table_ST16_method_comparison.csv",
    "output/table_ST17_pseudoprospective.csv",
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(8192), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    if not GOLDEN.is_dir():
        print("ERROR: golden/ directory does not exist.")
        return 1

    failures = 0
    matched = 0

    for relative_name in EXPECTED_FILES:
        golden_path = GOLDEN / relative_name
        actual_path = BASE / relative_name

        if not golden_path.is_file():
            print(f"MISSING GOLDEN: {relative_name}")
            failures += 1
            continue

        if not actual_path.is_file():
            print(f"MISSING OUTPUT: {relative_name}")
            failures += 1
            continue

        if sha256(golden_path) != sha256(actual_path):
            print(f"DIFF: {relative_name}")
            failures += 1
            continue

        print(f"MATCH: {relative_name}")
        matched += 1

    present_legacy = [
        relative_name
        for relative_name in RETIRED_LEGACY_FILES
        if (BASE / relative_name).is_file()
    ]
    for relative_name in present_legacy:
        print(f"IGNORED LEGACY: {relative_name}")

    print()
    print(
        f"SUMMARY: expected={len(EXPECTED_FILES)} "
        f"matched={matched} failed={failures}"
    )

    if failures:
        print("FAIL: active deterministic outputs differ from the golden baseline.")
        return 1

    print("OK: all active deterministic outputs match the golden baseline.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
